baseURL = 'https://krshubham.com/'
languageCode = 'en-us'
title = 'Kumar Shubham'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"
[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am a Tech Guy with a deep passion for building products that people love.
I am interested in a range of topics, including **Distributed Systems**, **Marathon Running** and just **life** in general.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '02 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/krshubham1708/"


[[params.social]]
name = "github"
url = "https://github.com/krshubham"

# Main menu pages
[[params.menu]]
name = "Home"
url = "/"

[[params.menu]]
name = "Posts"
url = "/posts"

[[params.menu]]
name = "About"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

[params]
showFooter = true
footerContent = "Written with ❤️ by Kumar Shubham"

[params]
mermaidTheme = "default"
mermaidDarkTheme = "dark"

